Why use Pandas ?
Ans: Pandas is used for Data processing, cleaning and analysis. It also used for high level data frame and structure data and table data.

In [1]:
import pandas as pd
import numpy as np

# Series

A series is one dimensional array that containing array of data,( of any NumPy datatype) and an associsted arrary of data label called index.

This is a simplest series to make format of array of data.

In [ ]:
series = pd.Series([90,89,100,23,45,900], index=(['a','b','c','d','e','f']), name=('Index'))
series.sort_values()
series[:-1]
# del series['a']
# series.pop('b')
series

0     90
1     89
    ...
4     45
5    900
Name: Index, Length: 6, dtype: int64

# Load data from file

In [3]:
df = pd.read_csv('annual-enterprise-survey-2024-financial-year-provisional.csv')

# Usage Attributes and functions

In [4]:
# It used to showing n column of data.
df.head(4)


# It tells pandas gives 5 last data
df.tail(1)

# retrieve column data
df.Year

# accessing level from data 
# df.Industry_aggregation_NZSIOC[:7]

# df.Value[:9]

#Gives maximum top data
df.max()

# maximum no. of column
pd.set_option('display.max_columns', 5)
# df

# maximum no. of row
pd.set_option('display.max_rows',4)
# df

# Get info of data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55620 entries, 0 to 55619
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Year                         55620 non-null  int64
 1   Industry_aggregation_NZSIOC  55620 non-null  str
 2   Industry_code_NZSIOC         55620 non-null  str
 3   Industry_name_NZSIOC         55620 non-null  str
 4   Units                        55620 non-null  str
 5   Variable_code                55620 non-null  str
 6   Variable_name                55620 non-null  str
 7   Variable_category            55620 non-null  str
 8   Value                        55620 non-null  str
 9   Industry_code_ANZSIC06       55620 non-null  str
dtypes: int64(1), str(9)
memory usage: 4.2 MB

In [5]:
df.shape
list(df.columns)

['Year',
 'Industry_aggregation_NZSIOC',
 'Industry_code_NZSIOC',
 'Industry_name_NZSIOC',
 'Units',
 'Variable_code',
 'Variable_name',
 'Variable_category',
 'Value',
 'Industry_code_ANZSIC06']

# Filtering a Boolean array

In [6]:
data = pd.Series(([20,34,5,45,34,65,76]), index=[[1,2,3,'a',5,6,7]])

data[data > 30]

# FIND INDEX IN VALUE
data[[6,2]]

'x' in data

False

# Indexing data to find missing or NaN values

NaN -> not a number

In [7]:
items = {'Computer':120000,
        'Marc Peter Desinorthn':5000,
        'Mastery In Python':4000,
        'Machine Learning':2000
        }

# data1 = ['AI/ML','Core Computer Knowledge', 'System Design', 'Mastery In Python']
# missing = pd.Series(items, index=data1) 

# # Any of them that function is used to find missing items
# missing.isna()
# missing.isnull()
# pd.notnull(missing)
# # pd.isnull(missing)

# Accessing multiple keys its values

In [8]:
index = np.arange(1,len(data)+1)
df = pd.DataFrame(items, index=index)
df[['Machine Learning',"Mastery In Python"]]

    Machine Learning  Mastery In Python
1               2000               4000
2               2000               4000
..               ...                ...
6               2000               4000
7               2000               4000

[7 rows x 2 columns]

# Use Series values as index

In [9]:
data.index = ['Apple', 'Google', 'OpenAI', 'Microsoft', 'Amazon', 'Akami', 'FaceBook']
data

Apple       20
Google      34
            ..
Akami       65
FaceBook    76
Length: 7, dtype: int64

# dict of Series

In [37]:
record = {'Computers':[120000, 10000, 90000],
        'Marc Peter Desinorthn':[5000,10000, 90000],
        'Mastery In Python':[4000,5000,10000],
        'Machine Learning':[2000, 4000,5000]
        }
index = np.arange(1, len(list(record.values())[0])+1)
df = pd.DataFrame(record, index=index)
df

   Computers  Marc Peter Desinorthn  Mastery In Python  Machine Learning
1     120000                   5000               4000              2000
2      10000                  10000               5000              4000
3      90000                  90000              10000              5000

# Load csv file

In [11]:
record = pd.read_csv('names.csv')
index = np.arange(1, len(record)+1)
df = pd.DataFrame(record, index=index)
df['email'][:5]

1       maryjacobs@bogusemail.com
2        davesmith@bogusemail.com
                 ...
4        tomwright@bogusemail.com
5    steverobinson@bogusemail.com
Name: email, Length: 5, dtype: str

# iloc -> ( full_name: Index location) using this method to access values of any specific index location.  In this case labeled keys index input

In [12]:
#            row,  column
record.iloc[[0,1,2,5], 2] # this gives column index 2 -> all 0 to 3 indices values of 2-index
# record.iloc[[1,2]]  # this way to return 1 to 2 all DataFrame values
# record.iloc[1:5, [0,2]]

0         john-doe@bogusemail.com
1       maryjacobs@bogusemail.com
2        davesmith@bogusemail.com
5    steverobinson@bogusemail.com
Name: email, dtype: str

# loc is used to label based on indexing and access rows and columns

In [13]:
record.loc[[0,3], 'last_name'] # this way to return 0 and 3 indices rows values of last_name
record.loc[1] # this way to manually return each values of 1-index row with keys-labels

record.loc[[1,3,5,6], ['first_name','email']] # each specify index values of specify keys-labels

record.loc[1:6, 'first_name':'email']

   first_name       last_name                         email
1        Mary  Smith-Robinson     maryjacobs@bogusemail.com
2        Dave           Smith      davesmith@bogusemail.com
..        ...             ...                           ...
5       Steve        Robinson  steverobinson@bogusemail.com
6      Nicole          Jacobs   nicolejacobs@bogusemail.com

[6 rows x 3 columns]